"""Advanced intent taxonomy.

A hierarchical map of domains -> verticals -> intents used by the
advanced router to classify natural-language requests across every
personal and business surface we care about.

Each intent is a lightweight, dependency-free record so the taxonomy
can be imported and scored anywhere without model or network calls.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Tuple


@dataclass(frozen=True)
class Intent:
    intent_id: str
    domain: str
    vertical: str
    label: str
    keywords: Tuple[str, ...]
    phrases: Tuple[str, ...] = field(default_factory=tuple)
    modalities: Tuple[str, ...] = ("text",)
    tools: Tuple[str, ...] = field(default_factory=tuple)
    skills: Tuple[str, ...] = field(default_factory=tuple)
    complexity: int = 2
    reasoning_depth: int = 2
    safety: str = "internal"
    regulated: bool = False
    agentic: bool = False
    long_context: bool = False


def _i(*args, **kwargs) -> Intent:
    return Intent(*args, **kwargs)


INTENTS: Tuple[Intent, ...] = (

    _i("personal.comm.email_draft", "personal", "communication", "Draft or reply to email",
       ("email", "reply", "inbox", "compose", "draft", "respond"),
       ("write an email", "reply to", "draft a response", "follow up with"),
       ("text",), ("email_api", "contacts"), ("COM-001",), 2, 2),
    _i("personal.comm.summary", "personal", "communication", "Summarize messages or threads",
       ("summarize", "tldr", "digest", "recap"),
       ("summarize this thread", "tl;dr", "recap yesterday"),
       ("text",), ("pdf_parser",), ("COM-004",), 2, 2),
    _i("personal.comm.tone", "personal", "communication", "Rewrite tone or style",
       ("rewrite", "tone", "polish", "paraphrase"),
       ("make it friendlier", "in my voice", "more concise"),
       ("text",), (), ("COM-005",), 1, 1),
    _i("personal.comm.translate", "personal", "communication", "Translate content",
       ("translate", "localize", "spanish", "french", "japanese"),
       ("translate to", "in another language"),
       ("text",), (), ("L10N-001",), 1, 1),
    _i("personal.comm.transcribe", "personal", "communication", "Transcribe audio",
       ("transcribe", "subtitles", "caption"),
       ("turn this recording into text",),
       ("audio",), ("asr",), ("CRE-007",), 2, 1),
    _i("personal.comm.voiceover", "personal", "communication", "Generate voiceover",
       ("voiceover", "read aloud", "narrate", "tts"),
       ("read this in a voice", "generate a voiceover"),
       ("audio",), ("tts",), ("CRE-006",), 2, 1),

    _i("personal.schedule.book", "personal", "scheduling", "Schedule a meeting or event",
       ("schedule", "book", "invite", "calendar", "meeting"),
       ("find time", "put on calendar", "block time"),
       ("tools",), ("calendar_api", "email_api"), ("COM-003",), 2, 2),
    _i("personal.schedule.reschedule", "personal", "scheduling", "Move or cancel events",
       ("reschedule", "move", "cancel", "postpone"),
       ("push the meeting", "cancel tomorrow's"),
       ("tools",), ("calendar_api",), ("COM-003",), 2, 2),

    _i("personal.todo.plan", "personal", "productivity", "Plan a day or project",
       ("plan", "organize", "todo", "priorities", "roadmap"),
       ("help me plan my week", "break this down"),
       ("text", "tools"), ("calendar_api",), ("OPS-006", "EDU-005"), 2, 3),
    _i("personal.focus.coach", "personal", "productivity", "Focus / ADHD coaching",
       ("focus", "adhd", "sprint", "pomodoro", "distracted"),
       ("help me focus", "break into sprints"),
       ("text", "tools"), ("timer", "calendar_api"), ("EDU-004",), 1, 2),

    _i("personal.finance.budget", "personal", "finance", "Personal budgeting",
       ("budget", "spending", "savings", "bills"),
       ("track my spending", "how much did i spend"),
       ("tools", "text"), (), ("DAT-004",), 2, 3, "confidential"),
    _i("personal.finance.tax", "personal", "finance", "Personal tax",
       ("tax", "1099", "w2", "deduction", "irs"),
       ("file my taxes", "itemize deductions"),
       ("tools", "text"), (), ("DAT-004",), 3, 4, "regulated", True),
    _i("personal.finance.invest", "personal", "finance", "Personal investing",
       ("portfolio", "stocks", "etf", "401k", "invest"),
       ("rebalance my portfolio", "should i buy"),
       ("text", "tools"), (), ("DAT-006",), 3, 4, "regulated", True),

    _i("personal.travel.plan", "personal", "travel", "Travel planning",
       ("flight", "hotel", "itinerary", "trip", "travel"),
       ("plan a trip to", "book a flight"),
       ("text", "tools"), ("browser", "serp"), (), 2, 2),
    _i("personal.health.coach", "personal", "health", "Health or fitness coaching",
       ("workout", "diet", "symptom", "sleep", "fitness"),
       ("design a workout", "track my sleep"),
       ("text", "tools"), (), (), 2, 2, "regulated", True),
    _i("personal.health.medical", "personal", "health", "Medical information",
       ("medication", "diagnosis", "doctor", "prescription", "condition"),
       ("what does this symptom mean", "drug interactions"),
       ("text",), (), (), 3, 4, "regulated", True),

    _i("personal.home.smart", "personal", "home", "Smart home control",
       ("lights", "thermostat", "smart home", "hvac", "lock"),
       ("turn off the lights", "set the thermostat"),
       ("tools",), (), (), 1, 1),
    _i("personal.shopping.research", "personal", "shopping", "Shopping research",
       ("review", "buy", "compare", "price", "deal"),
       ("which one should i buy", "find the best"),
       ("text", "tools"), ("browser", "serp"), ("SLS-004",), 2, 2),

    _i("personal.education.tutor", "personal", "education", "Tutor / learn a concept",
       ("teach", "explain", "tutor", "learn", "concept"),
       ("explain like i'm five", "walk me through"),
       ("text",), (), ("EDU-003",), 2, 3),
    _i("personal.education.quiz", "personal", "education", "Quiz or flashcards",
       ("quiz", "flashcards", "test me", "practice"),
       ("make a quiz", "flashcards on"),
       ("text", "tools"), ("quiz_gen",), ("EDU-002",), 1, 2),

    _i("biz.sales.prospect", "business", "sales", "Prospect research",
       ("prospect", "account", "firmographic", "icp", "lead"),
       ("research this company", "build a target list"),
       ("tools", "text"), ("browser", "serp", "crm_api"), ("SLS-001",), 3, 3, agentic=True),
    _i("biz.sales.qualify", "business", "sales", "Opportunity qualification",
       ("qualify", "meddic", "discovery", "bant", "champ"),
       ("qualify this deal", "meddpicc review"),
       ("text", "tools"), ("crm_api",), ("SLS-002",), 2, 3),
    _i("biz.sales.proposal", "business", "sales", "Proposal / POV",
       ("proposal", "pov", "sow", "rfp", "quote"),
       ("draft a proposal", "build a POV"),
       ("text",), ("doc_gen", "brand_styles"), ("SLS-003",), 3, 4),
    _i("biz.sales.competitive", "business", "sales", "Competitive intel",
       ("competitor", "battlecard", "positioning", "differentiator"),
       ("compare us to", "battlecard for"),
       ("tools", "text"), ("browser", "serp"), ("SLS-004",), 3, 3),
    _i("biz.sales.sequence", "business", "sales", "Outbound sequence",
       ("sequence", "cadence", "outbound", "campaign"),
       ("build a sequence", "write a cold email"),
       ("text", "tools"), ("email_api", "marketing_api"), ("SLS-005",), 2, 2),
    _i("biz.sales.roleplay", "business", "sales", "Sales role-play",
       ("role-play", "discovery call", "objection"),
       ("practice this call", "role play"),
       ("audio", "text"), ("tts", "asr"), ("SLS-006",), 3, 3),

    _i("biz.marketing.copy", "business", "marketing", "Marketing copy",
       ("headline", "ad copy", "landing page", "blog"),
       ("write a headline", "blog post about"),
       ("text",), (), ("CRE-005",), 2, 2),
    _i("biz.marketing.seo", "business", "marketing", "SEO / content plan",
       ("seo", "keywords", "content calendar", "serp"),
       ("rank for", "keyword research"),
       ("tools", "text"), ("browser", "serp"), (), 2, 3),
    _i("biz.marketing.brand", "business", "marketing", "Brand / design",
       ("brand", "logo", "palette", "style guide"),
       ("logo concept", "brand colors"),
       ("vision", "text"), ("design_api",), ("CRE-003",), 3, 2),
    _i("biz.marketing.image", "business", "marketing", "Image generation",
       ("image", "hero", "banner", "generate a picture"),
       ("make an image", "visual of"),
       ("vision",), ("t2i",), ("CRE-001",), 2, 1),
    _i("biz.marketing.video", "business", "marketing", "Video generation",
       ("video", "clip", "reel", "short"),
       ("make a video", "generate a clip"),
       ("vision",), ("t2v",), ("CRE-002",), 3, 2),

    _i("biz.ops.rag", "business", "operations", "RAG / document Q&A",
       ("contract", "policy", "document", "lookup", "find in docs"),
       ("what does this contract say", "answer from the handbook"),
       ("text", "vision", "tools"), ("pdf_parser", "vector_search", "table_ocr"),
       ("OPS-001",), 3, 4, long_context=True),
    _i("biz.ops.contract_risk", "business", "operations", "Contract risk analysis",
       ("contract risk", "redline", "clause", "nda", "msa"),
       ("flag risky clauses", "compare this msa"),
       ("text",), ("pdf_parser",), ("OPS-002",), 3, 4, regulated=True, long_context=True),
    _i("biz.ops.kb_build", "business", "operations", "Knowledge base build",
       ("index docs", "build knowledge base", "embed", "vectorize"),
       ("set up a kb", "index these files"),
       ("tools",), ("vector_search", "embedder"), ("OPS-003",), 2, 2),
    _i("biz.ops.compliance", "business", "operations", "Policy compliance scan",
       ("gdpr", "pii", "sox", "hipaa", "compliance"),
       ("scan for pii", "gdpr review"),
       ("text",), ("text_scanner",), ("OPS-004", "GOV-004"), 3, 4, regulated=True),
    _i("biz.ops.sop", "business", "operations", "SOP / handover",
       ("sop", "runbook", "handover", "standard operating"),
       ("write a runbook", "document this process"),
       ("text",), ("doc_gen",), ("OPS-005",), 2, 2),
    _i("biz.ops.project", "business", "operations", "Project plan / Gantt",
       ("gantt", "project plan", "milestone", "dependencies"),
       ("build a project plan", "12 week plan"),
       ("tools", "text"), ("project_api", "csv_export"), ("OPS-006",), 2, 3),
    _i("biz.ops.change", "business", "operations", "Change management",
       ("changelog", "release notes", "semver", "diff releases"),
       ("generate a changelog", "release notes for"),
       ("tools", "text"), ("repo_api",), ("OPS-007",), 2, 2),

    _i("biz.eng.bugfix", "business", "engineering", "Code patch / bug fix",
       ("bug", "patch", "fix", "failing test", "regression"),
       ("fix the failing test", "patch this bug"),
       ("text", "tools"), ("repo_reader", "unit_test_runner", "diff_applier"),
       ("ENG-001",), 4, 4, agentic=True),
    _i("biz.eng.refactor", "business", "engineering", "Refactor / codegen",
       ("refactor", "rewrite", "codegen", "generate code"),
       ("refactor this module", "write a function"),
       ("text", "tools"), ("repo_reader", "static_analysis"), ("ENG-002",), 4, 4),
    _i("biz.eng.review", "business", "engineering", "Code review",
       ("code review", "pull request", "pr review"),
       ("review this pr", "review my code"),
       ("text",), ("repo_reader",), ("GOV-002",), 3, 4),
    _i("biz.eng.firmware", "business", "engineering", "Firmware / embedded",
       ("firmware", "embedded", "arduino", "stm32", "mcu"),
       ("write firmware", "pin map"),
       ("text",), (), ("ENG-003",), 4, 4),
    _i("biz.eng.robotics", "business", "engineering", "Robotics / ROS",
       ("ros", "ros2", "robot", "urdf", "launch file"),
       ("ros2 launch", "robot behavior"),
       ("text", "tools"), ("diagram_export",), ("ENG-004",), 4, 4),
    _i("biz.eng.cad", "business", "engineering", "CAD / 3D prototype",
       ("cad", "stl", "3d print", "bambu", "mesh"),
       ("design a 3d print", "stl for"),
       ("tools",), ("cad_gen", "stl_validator"), ("ENG-005",), 4, 3),
    _i("biz.eng.simulation", "business", "engineering", "Simulation / digital twin",
       ("simulate", "digital twin", "monte carlo", "sensitivity"),
       ("simulate the system", "run a sensitivity"),
       ("tools", "text"), ("sim_engine",), ("ENG-006",), 4, 5),
    _i("biz.eng.qa", "business", "engineering", "QA / regression",
       ("regression", "coverage", "qa", "test suite"),
       ("run qa", "coverage delta"),
       ("tools",), ("ci_runner",), ("ENG-007",), 3, 3),
    _i("biz.eng.deploy", "business", "engineering", "Release / rollback",
       ("deploy", "rollback", "canary", "blue green"),
       ("canary deploy", "rollback the release"),
       ("tools",), ("deploy_api",), ("ENG-008", "SYS-007"), 3, 3),
    _i("biz.eng.security", "business", "engineering", "Security review",
       ("vulnerability", "cve", "sast", "dast", "security review"),
       ("scan for vulns", "security review of"),
       ("tools", "text"), ("static_analyzer",), ("GOV-002",), 4, 4, regulated=True),

    _i("biz.data.etl", "business", "data", "ETL / cleaning",
       ("etl", "clean", "dedupe", "snowflake", "pipeline"),
       ("clean this dataset", "dedupe rows"),
       ("tools",), ("etl_tool",), ("DAT-001",), 2, 2),
    _i("biz.data.viz", "business", "data", "Data visualization",
       ("chart", "dashboard", "graph", "kpi", "visualize"),
       ("chart this data", "build a dashboard"),
       ("tools", "text"), ("bi_api", "chart_export"), ("DAT-002",), 2, 2),
    _i("biz.data.forecast", "business", "data", "Forecasting",
       ("forecast", "predict", "time series", "arima", "prophet"),
       ("forecast revenue", "predict churn"),
       ("tools", "text"), ("python_runner",), ("DAT-003",), 3, 4),
    _i("biz.data.sql", "business", "data", "SQL / analytics",
       ("sql", "query", "warehouse", "bigquery", "aggregate"),
       ("write a sql", "query the warehouse"),
       ("text", "tools"), (), (), 3, 3),
    _i("biz.data.ml_train", "business", "data", "Model training",
       ("train model", "fine-tune", "classification", "regression"),
       ("train a classifier", "fine-tune a model"),
       ("tools", "text"), ("python_runner",), ("DAT-003",), 4, 5),

    _i("biz.finance.model", "business", "finance", "Financial modeling",
       ("cashflow", "tam sam som", "cap table", "valuation"),
       ("build a financial model", "cap table for"),
       ("tools", "text"), ("excel_api",), ("DAT-004",), 3, 4, regulated=True),
    _i("biz.finance.roi", "business", "finance", "ROI / scenarios",
       ("roi", "scenario", "npv", "irr"),
       ("roi analysis", "scenario modeling"),
       ("tools", "text"), ("sim_engine",), ("DAT-006",), 3, 4),
    _i("biz.finance.cost_opt", "business", "finance", "Cost optimization",
       ("cost optimization", "vendor arbitrage", "unit economics"),
       ("cheaper alternatives", "reduce spend"),
       ("tools",), ("router_logs",), ("DAT-005",), 2, 3),

    _i("biz.hr.jobdesc", "business", "hr", "Job description / JD",
       ("job description", "jd", "hire", "role scorecard"),
       ("write a job description", "scorecard for"),
       ("text",), (), (), 2, 2),
    _i("biz.hr.interview", "business", "hr", "Interview prep",
       ("interview", "candidate", "screening", "rubric"),
       ("interview questions", "evaluate candidate"),
       ("text",), (), (), 2, 3),
    _i("biz.hr.policy", "business", "hr", "HR policy",
       ("pto", "handbook", "leave", "benefits"),
       ("update handbook", "pto policy"),
       ("text",), (), ("OPS-005",), 2, 3, regulated=True),

    _i("biz.legal.draft", "business", "legal", "Legal drafting",
       ("contract", "agreement", "nda", "terms"),
       ("draft an nda", "terms of service"),
       ("text",), (), ("OPS-002",), 3, 4, regulated=True, long_context=True),
    _i("biz.legal.research", "business", "legal", "Legal research",
       ("case law", "statute", "jurisdiction", "precedent"),
       ("find case law", "legal research on"),
       ("text", "tools"), ("browser",), (), 4, 5, regulated=True),

    _i("biz.govrisk.audit", "business", "governance", "Audit / trail",
       ("audit trail", "provenance", "attestation"),
       ("prove what ran", "audit log"),
       ("tools",), ("audit_store",), ("GOV-003",), 2, 2, regulated=True),
    _i("biz.govrisk.bias", "business", "governance", "Bias / fairness",
       ("bias", "fairness", "demographic parity", "disparate"),
       ("audit for bias", "fairness check"),
       ("tools", "text"), ("bias_checker",), ("GOV-001",), 3, 4),
    _i("biz.govrisk.reg", "business", "governance", "Regulatory gap",
       ("regulation", "regulatory", "eu ai act", "nist"),
       ("map to eu ai act", "regulatory gap"),
       ("text", "tools"), ("policy_db",), ("GOV-004",), 4, 5, regulated=True),

    _i("biz.a11y", "business", "accessibility", "Accessibility audit",
       ("wcag", "a11y", "screen reader", "contrast"),
       ("a11y audit", "wcag check"),
       ("tools", "text"), ("a11y_scanner",), ("L10N-003",), 2, 2),
    _i("biz.l10n.qa", "business", "localization", "Localization QA",
       ("locale", "i18n", "string overflow", "translation qa"),
       ("l10n qa", "date formats per locale"),
       ("tools",), ("ui_crawler",), ("L10N-002",), 2, 2),

    _i("biz.creative.deck", "business", "creative", "Slide deck",
       ("deck", "slides", "presentation", "pitch"),
       ("build a deck", "pitch slides"),
       ("text", "tools"), ("ppt_api",), ("CRE-004",), 2, 3),
    _i("biz.creative.story", "business", "creative", "Storyboard / script",
       ("storyboard", "script", "screenplay", "beats"),
       ("write a script", "storyboard for"),
       ("text",), (), ("CRE-005",), 2, 3),

    _i("biz.vertical.bx", "business", "vertical", "Siemens BX / building automation",
       ("siemens", "bx", "building automation", "desigo", "bms"),
       ("siemens bx pov", "building automation"),
       ("text", "tools"), ("pdf_parser", "vector_search", "ppt_api"),
       ("DSP-001",), 3, 4),
    _i("biz.vertical.construction", "business", "vertical", "Construction / controls",
       ("controls contractor", "submittal", "bom", "construction"),
       ("controls submittal", "bom estimate"),
       ("text", "tools"), ("pdf_parser", "cad_gen"), ("DSP-002",), 3, 3),
    _i("biz.vertical.saas_sales", "business", "vertical", "SaaS sales enablement",
       ("saas sales", "enablement", "battlecard"),
       ("saas enablement pack",),
       ("text", "tools"), ("crm_api", "email_api"), ("DSP-003",), 3, 3),
    _i("biz.vertical.healthcare", "business", "vertical", "Healthcare workflows",
       ("hipaa", "ehr", "clinical", "patient", "icd"),
       ("clinical summary", "hipaa workflow"),
       ("text", "tools"), (), (), 4, 5, regulated=True),
    _i("biz.vertical.finserv", "business", "vertical", "Financial services",
       ("kyc", "aml", "banking", "finserv", "trading"),
       ("kyc workflow", "aml rules"),
       ("text", "tools"), (), (), 4, 5, regulated=True),
    _i("biz.vertical.manufacturing", "business", "vertical", "Manufacturing / IoT",
       ("oee", "scada", "plc", "manufacturing", "iiot"),
       ("oee dashboard", "plc logic"),
       ("tools", "text"), (), (), 3, 4),
    _i("biz.vertical.retail", "business", "vertical", "Retail / ecommerce",
       ("ecommerce", "sku", "inventory", "merchandising"),
       ("pdp copy", "merchandising plan"),
       ("text", "tools"), (), (), 2, 2),
    _i("biz.vertical.education", "business", "vertical", "EdTech / learning",
       ("course", "curriculum", "lesson plan", "lms"),
       ("build a course", "curriculum for"),
       ("text", "tools"), ("ppt_api", "quiz_gen"), ("EDU-001",), 2, 3),
    _i("biz.vertical.realestate", "business", "vertical", "Real estate",
       ("listing", "mls", "real estate", "cap rate"),
       ("listing copy", "real estate analysis"),
       ("text", "tools"), (), (), 2, 2),
    _i("biz.vertical.legal_vertical", "business", "vertical", "Legal vertical",
       ("litigation", "discovery", "deposition"),
       ("deposition prep", "discovery review"),
       ("text", "tools"), (), (), 4, 5, regulated=True, long_context=True),
    _i("biz.vertical.publicsector", "business", "vertical", "Public sector",
       ("fedramp", "cjis", "public sector", "government"),
       ("fedramp controls", "rfi for gov"),
       ("text",), (), (), 4, 5, regulated=True),
    _i("biz.vertical.energy", "business", "vertical", "Energy / utilities",
       ("grid", "utility", "energy", "solar", "battery"),
       ("demand response", "energy audit"),
       ("tools", "text"), (), (), 3, 4),
    _i("biz.vertical.logistics", "business", "vertical", "Logistics / supply chain",
       ("logistics", "supply chain", "routing", "warehouse"),
       ("route optimization", "supply chain plan"),
       ("tools", "text"), (), (), 3, 4),

    _i("biz.sys.monitor", "business", "system", "Model health monitoring",
       ("drift", "monitor", "latency", "anomaly"),
       ("monitor the models", "drift alert"),
       ("tools",), ("metrics_store",), ("SYS-001",), 2, 2),
    _i("biz.sys.tune", "business", "system", "Self-critique / auto-tune",
       ("auto tune", "prompt optimization", "self critique"),
       ("tune the prompts", "self improve"),
       ("tools", "text"), ("tuner", "router_logs"), ("SYS-002",), 4, 5, agentic=True),
    _i("biz.sys.feedback", "business", "system", "Feedback capture",
       ("feedback", "thumbs", "rating", "reinforcement"),
       ("capture feedback", "reweight"),
       ("tools",), ("feedback_db",), ("SYS-003",), 1, 1),
    _i("biz.sys.bench", "business", "system", "Benchmark sync",
       ("benchmark", "leaderboard", "arena", "livebench"),
       ("pull arena", "refresh leaderboard"),
       ("tools",), ("bench_ingestors",), ("SYS-004",), 1, 1),
    _i("biz.sys.slo", "business", "system", "Cost / latency arbitration",
       ("slo", "sla", "latency budget", "arbitration"),
       ("enforce sla", "latency budget"),
       ("tools",), ("router",), ("SYS-005",), 2, 2),
    _i("biz.sys.roi", "business", "system", "Skill ROI analysis",
       ("skill roi", "utilization", "retire skill"),
       ("which skills to kill", "roi by skill"),
       ("tools",), ("analytics",), ("SYS-006",), 2, 2),
)


def group_by_domain() -> Dict[str, List[Intent]]:
    out: Dict[str, List[Intent]] = {}
    for i in INTENTS:
        out.setdefault(i.domain, []).append(i)
    return out


def group_by_vertical() -> Dict[str, List[Intent]]:
    out: Dict[str, List[Intent]] = {}
    for i in INTENTS:
        out.setdefault(i.vertical, []).append(i)
    return out


def by_id() -> Dict[str, Intent]:
    return {i.intent_id: i for i in INTENTS}
